version: 3.9
services:
 mysql:
 image: mysql:8.0
 container_name: freshcart-mysql
 restart: unless-stopped
 environment:
 MYSQL_DATABASE: freshcart_db
 MYSQL_ROOT_PASSWORD: root
 MYSQL_USER: freshcart
 MYSQL_PASSWORD: freshcart
 ports:
 - 3306:3306
 volumes:
 - db_data:/var/lib/mysql
 phpmyadmin:
 image: phpmyadmin:5
 container_name: freshcart-phpmyadmin
 restart: unless-stopped
 environment:
 PMA_HOST: mysql
 PMA_USER: root
 PMA_PASSWORD: root
 ports:
 - 8081:80
 depends_on:
 - mysql
 backend:
 build: .
 container_name: freshcart-backend
 environment:
 DB_USERNAME: freshcart
 DB_PASSWORD: freshcart
 JWT_SECRET: supersecretjwtkeysupersecretjwtkey
 ports:
 - 8080:8080
 depends_on:
 - mysql
volumes:
 db_data:
